networks:
  statistics_network:

services:
  nginx:
    image: 1.27.2-alpine
    ports:
      - "80:8080"
  backend:
    image: backend.statistics
    ports:
      - "50055:50055"
    networks:
      - statistics_network
    build:
      context: .
      dockerfile: Backend.Statistics/Dockerfile
    depends_on:
      - postgres
      - keydb
      - nginx
  parser:
    image: parser.statistics
    networks:
      - statistics_network
    build:
      context: .
      dockerfile: Parser.Statistics/Dockerfile
    depends_on:
      - postgres
      - keydb
  postgres:
    image: 17.0-alpine3.20
    ports:
       - "5432:5432"
    networks:
      - statistics_network
  keydb:
    image: eqalpha/keydb
    ports:
      - "6379:6379"
    entrypoint: [""]
    volumes:
      - redis-data:/data
    networks:
      - statistics_network